// Disable top LED
#undef RGBLED_NUM
#define RGBLED_NUM 10

// Restore sane defaults
#undef RGBLIGHT_HUE_STEP
#undef RGBLIGHT_SAT_STEP
#undef RGBLIGHT_VAL_STEP

#define OLED_UPDATE_INTERVAL 10
// #define OLED_SHOW_FPS

#define TAPPING_TERM 150
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD
#define TAPPING_FORCE_HOLD_PER_KEY
