NKRO_ENABLE = yes
LTO_ENABLE = yes
RAW_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = yes

CONSOLE_ENABLE = no
#DEBUG_MATRIX_SCAN_RATE_ENABLE = yes
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
